name: Monitor Repo2 for New Commits and Sync to Repo1

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Identity
        run: |
          git config --global user.email "vasylkiv.t@gmail.com"
          git config --global user.name "vasylkiv-t"

      - name: Checkout Repo2
        uses: actions/checkout@v3
        with:
          repository: vasylkiv-t/auto-merge-2
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: auto-merge-2
          fetch-depth: 0

      - name: Create New Branch in Repo1
        run: |
          cd auto-merge-2
          git clone https://vasylkiv-t:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/vasylkiv-t/auto-merge.git ../auto-merge
          cd ../auto-merge
          NEW_BRANCH="sync-branch-$(date +%s)"
          git checkout -b $NEW_BRANCH
          git remote add auto-merge-2 ../auto-merge-2
          git fetch auto-merge-2
          git merge auto-merge-2/main -m "Merge changes from repo2" --allow-unrelated-histories || true
          git push origin $NEW_BRANCH

      - name: Create Pull Request in Repo1
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "Sync changes from repo2"
          title: "Automated Sync from repo2"
          body: "This pull request contains changes synced from repo2 to repo1."
          branch: $NEW_BRANCH
          committer: GitHub <noreply@github.com>
          author: vasylkiv-t <vasylkiv-t@users.noreply.github.com>
          signoff: false
          delete-branch: false
          draft: false

